config/routes.rb
Rails.application.routes.draw do
  root "customers#index"
  
  devise_for :users

  get '/search', to: 'search#index'
  
  resources :customers do
    resources :product_item_dates, except: [:index, :show] do
      resources :product_items, except: [:index, :show], path: 'purchase'
    end
  end

  resources :products

  resources :stores

end

app/models/store.rb
# == Schema Information
#
# Table name: stores
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_stores_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Store < ApplicationRecord
  belongs_to :user

  validates_presence_of :name

  has_many :products

  has_many :store_products
  has_many :products, through: :store_products
  
  has_many :product_items

  scope :ordered, -> { order(created_at: :desc) }

  def all_store_products
    products
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
    before_action :find_store, only: [:show, :edit, :update, :destroy]
    before_action :set_products, only: [:new, :edit]

    def index
        @stores = Store.ordered
    end

    def show
        
    end

    def new
        @store = Store.new
    end

    def create
        @store = current_user.stores.build(store_params)
        if @store.save
            redirect_to edit_store_url(@store), notice: "Product created successfully, add products to your store"
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        
    end

    def update
        if @store.update(store_params)
            flash[:notice] = "Store updated successfully"
            redirect_to store_url(@store)
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @store.destroy
        flash[:notice] = "Store has been successfully destroyed"
    end

    private

        def store_params
            params.require(:store).permit(:name, product_ids: [])
        end

        def find_store
            @store ||= Store.find(params[:id])
        end

        def set_products
            # @products ||= Product.where(store: @store).order(:name) + Product.where(store_id: nil)
            @products ||= Product.all
        end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_empty_state.html.erb
<div class="empty-state">
  <p class="empty-state__text">
    You have not created any store yet!
  </p>

  <%= link_to "Create store", new_store_path, class: "butn butn--primary" if admin?(current_user) %>
</div>

app/views/stores/_form.html.erb
<%= simple_form_for store, wrapper: :inline_form, html: { class: "customer form" } do |f| %>
    
    <%= f.error_notification %>

    <%= f.input :name, input_html: { autofocus: true, placeholder: 'Store name' }, label: false %>

    <% unless f.object.new_record? %>
        Add products to your store. <small class="text-info">You must have your products created before selection. <%= link_to 'Click here', new_product_path, target: '_blank' %> to create new product.</small>
        <div data-controller="tom-select">
            <%= f.input :product_ids, as: :select, collection: (@products), label_method: :name, input_html: { placeholder: "Select store products", multiple: true, id: "select-products", class: 'products' }, label: false %>
        </div>
    <% end %>

    <%= link_to stores_path, class: "butn butn--light" do %>
        <%= image_tag "x.png", width: "19" %>
    <% end %>

    <%= button_tag type: 'Submit', class: "butn butn--secondary mt-1" do %>
        <%= image_tag "check.png", width: "19" %>
    <% end %>
<% end %>

app/views/stores/_store.html.erb
<div class="customer col-12 justify-content-between d-flex align-items-center">
    <%= link_to store.name, store_path(store) %>
    <% if admin?(current_user) %>
      <span class="customer__actions">
        <%= link_to store_path(store), class: "butn butn--light" do %>
          <%= image_tag "eye.png", size: "25" %>
        <% end %>
        
        <%= link_to edit_store_path(store), class: "butn butn--light" do %>
          <%= image_tag "edit.png", size: "25" %>
        <% end %>
      </span>
    <% end %>
</div>

app/views/stores/edit.html.erb
<main class="container">
    <%= link_to sanitize("&larr; Back to stores"), stores_path %>

    <div class="header">
        <h1>Edit store</h1>
    </div>

    <%= render "form", store: @store %>
</main>

app/views/stores/index.html.erb
<main class="container">
    <div class="header">
        <h1><i class="bi bi-shop"></i> Stores</h1>
            <span><%= link_to "Create store", new_store_path, class: "butn butn--primary" if admin?(current_user) %></span>
    </div>

    <% if @stores.none? %>
        <%= render "stores/empty_state" %>
    <% end %>

    <div class="row">
        <%= render @stores %>
    </div>
</main>

app/views/stores/new.html.erb
<main class="container">
    <%= link_to sanitize("&larr; Back to stores"), stores_path %>

    <div class="header">
        <h1>New Store</h1>
    </div>

    <%= render "form", store: @store %>
</main>

app/views/stores/show.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to stores"), stores_path %>
  
  <p class="text-muted">Store created by: <%= @store.user.email %></p>

  <div class="header">
    <h1>
      <%= @store.name %>
    </h1>

    <span>
      <%= link_to "Edit store", edit_store_path(@store), class: "butn butn--primary" if admin?(current_user) %>
    </span>
  </div>

  <h3>Store products</h3>

  <div class="store-products">
    <table class="table table-bordered rounded overflow-hidden my-3">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Qty</th>
                <th scope="col">Code</th>
                <th scope="col">created by</th>
            </tr>
        </thead>
        <tbody>
          <% @store.products.each do |p| %>
            <tr class="fw-normal">
                <td><%= link_to p.name, p %></td>
                <td><%= p.quantity %></td>
                <td><%= p.code %></td>
                <td><%= p.user.email %></td>
            </tr>
          <% end %>
        </tbody>
    </table>
  </div>
</main>