config/routes.rb
Rails.application.routes.draw do
  root "customers#index"
  
  devise_for :users

  get '/search', to: 'search#index'
  
  resources :customers do
    resources :product_item_dates, except: [:index, :show] do
      resources :product_items, except: [:index, :show], path: 'purchase'
    end
  end

  resources :products

  resources :stores

end

app/models/customer.rb
# == Schema Information
#
# Table name: customers
#
#  id           :bigint           not null, primary key
#  name         :string
#  phone_number :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  user_id      :bigint           not null
#
# Indexes
#
#  index_customers_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Customer < ApplicationRecord
  validates_presence_of :name, :phone_number

  belongs_to :user
  
  has_many :product_item_dates, dependent: :destroy  
  
  has_many :product_items, through: :product_item_dates
  
  paginates_per 8

  scope :ordered, -> { order(id: :desc) }

  scope :namee, -> (name) { where("lower(name) like ?", "%#{name.downcase}%") }

  # scope :total_outstanding, -> { where(total_unpaid > 0) }

  # tatal amount of purchased products
  def total_price
    product_items.sum(&:total_price)
  end

  # customer debt
  def unpaid
    # product_items.where(payment_status: 'unpaid').sum(&:total_price)
    product_items.sum(&:outstanding_price)
  end

  # total amount paid by customer
  def paid
    total_paid = total_price - unpaid
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
    before_action :set_customer, only: [:show, :edit, :update, :destroy]

    def index
<<<<<<< HEAD
        @customers = Customer.all.ordered.page(params[:page])
=======
        @customers = Customer.ordered
>>>>>>> c4b797f8e412fc01ec60384b61439adf3303a238
    end

    def show
        @product_item_dates = @customer.product_item_dates.includes(:product_items).ordered
        # debugger
    end

    def new
        @customer = Customer.new
    end

    def create
        @customer = current_user.customers.build(customer_params)
        if @customer.save
            respond_to do |format|
                format.html { redirect_to customers_url, notice: 'Customer was successfully created' }
                format.turbo_stream { flash.now[:notice] = "Customer was successfully created" }
            end
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        
    end

    def update
        if @customer.update(customer_params)
            respond_to do |format|
                format.html { redirect_to customers_url, notice: 'Customer was successfully updated' }
                format.turbo_stream { flash.now[:notice] = "Customer was successfully updated" }
            end
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @customer.destroy
        respond_to do |format|
            format.html { redirect_to customers_url, notice: 'Customer was successfully deleted' }
            # format.turbo_stream { flash.now[:notice] = "Customer was successfully deleted" }
        end
    end

    private

    def customer_params
        params.require(:customer).permit(:name, :phone_number)
    end

    def set_customer
        @customer ||= Customer.find(params[:id])
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer.html.erb
<%= turbo_frame_tag customer do %>
  <div class="customer col-12 justify-content-between d-flex align-items-center">
    <%= link_to customer.name, customer_path(customer), data: { turbo_frame: "_top" } %>
    <% if authorized_user?(current_user) %>
      <span class="customer__actions">
        <%= link_to customer_path(customer), data: { "turbo-method": :delete, turbo_frame: "_top", turbo_confirm: "Are you sure?" }, class: "butn butn--light" do %>
          <%= image_tag "delete.png", size: "25" %>
        <% end %>
        <%= link_to edit_customer_path(customer), class: "butn butn--light" do %>
          <%= image_tag "edit.png", size: "25" %>
        <% end %>
      </span>
    <% end %>
  </div>
<% end %>

app/views/customers/_empty_state.html.erb
<div class="empty-state">
  <p class="empty-state__text">
    You don't have any customers yet!
  </p>

  <%= link_to "Add customer", new_customer_path, class: "butn butn--primary" if admin?(current_user) %>
</div>

app/views/customers/_form.html.erb
<%= simple_form_for customer, wrapper: :inline_form, html: { class: "customer form" } do |f| %>
    <%= f.error_notification %>
    <div class="row row-cols-auto">
        <div class="col form-col-1">
            <%= f.input :name, input_html: { autofocus: true, placeholder: 'Customer name' }, class: "input", label: false %>
        </div>
        <div class="col form-col-2">
            <%= f.input :phone_number, input_html: { autofocus: true, placeholder: 'Phone number' }, label: false %>
        </div>
        <div class="col form-col">
            <%= link_to customers_path, class: "butn butn--light" do %>
                <%= image_tag "x.png", width: "19" %>
            <% end %>
        </div>
        <div class="col form-col">
            <%= button_tag type: 'submit', class: "butn butn--secondary" do %>
                <%= image_tag "check.png", size: "19" %>
            <% end %>
        </div>
    </div>
<% end %>

app/views/customers/_total.html.erb
<footer class="customer-total">
  <div class="row" style="max-width: 60rem; margin: 0 auto;">
    <div class="col-4">
      <h6>Total: <%= number_to_currency(customer.total_price, unit: "₦") %></h6>
    </div>
    <div class="col-4">
      <h6>Total Outstanding: <%= number_to_currency(customer.unpaid, unit: "₦") %></h6>
    </div>
    <div class="col-4">
      <h6>Total paid: <%= number_to_currency(customer.paid, unit: "₦") %></h6>
    </div>
  </div>
</footer>

app/views/customers/create.turbo_stream.erb
<%= turbo_stream.prepend "customers", @customer %>
<%= turbo_stream.update Customer.new, "" %>
<%= render_turbo_stream_flash_messages %>

app/views/customers/destroy.turbo_stream.erb
<%= turbo_stream.remove @customer %>
<%= render_turbo_stream_flash_messages %>

<% unless current_user.customers.exists? %>
  <%= turbo_stream.update Customer.new do %>
    <%= render "customers/empty_state" %>
  <% end %>
<% end %>

app/views/customers/edit.html.erb
<main class="container">
    <%= link_to sanitize("&larr; Back to customers"), customers_path %>

    <div class="header">
        <h1>Edit customer</h1>
    </div>

    <%= turbo_frame_tag @customer do %>
        <%= render "form", customer: @customer %>
    <% end %>
</main>

app/views/customers/index.html.erb
<main class="container">
    <div class="header">
        <h1><i class="bi bi-people"></i> Customers</h1>
        <span><%= link_to "Add customer", new_customer_path, class: "butn butn--primary", data: { turbo_frame: dom_id(Customer.new) } if authorized_user?(current_user) %></span>
    </div>

    <% unless @customers.blank? %>
        <div class="header search">
            <%= render 'layouts/customer_search' %>
        </div>
    <% end %>

    <%= turbo_frame_tag Customer.new do %>
        <% if @customers.none? %>
            <%= render "customers/empty_state" %>
        <% end %>
    <% end %>

    <%= turbo_frame_tag "customers" do %>
        <div class="row">
            <%= render @customers %>
        </div>
    <% end %>
    
    <%= paginate @customers, window: 2, theme: 'bootstrap-5',
                    pagination_class: "pagination-sm flex-wrap justify-content-center",
                    nav_class: "d-inline-block" %>
</main>

app/views/customers/new.html.erb
<main class="container">
    <%= link_to sanitize("&larr; Back to customers"), customers_path %>

    <div class="header">
        <h1>New customer</h1>
    </div>

    <%= turbo_frame_tag @customer do %>
        <%= render "form", customer: @customer %>
    <% end %>
</main>

app/views/customers/search.html.erb
<h1>Search results</h1>

<%= render @customers if @customers.present? %>

app/views/customers/show.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to customers"), customers_path %>
  
  <p class="text-muted">Customer created by: <%= @customer.user.email %></p>

  <div class="header">
    <h1>
      <%= @customer.name %>
    </h1>

    <span>
      <%= link_to "New date", new_customer_product_item_date_path(@customer), data: { turbo_frame: dom_id(ProductItemDate.new) }, class: "butn butn--primary" if admin?(current_user) %>
    </span>
  </div>

  <%= turbo_frame_tag ProductItemDate.new %>

  <%= turbo_frame_tag "product_item_dates" do %>
    <%= render @product_item_dates, customer: @customer %>
  <% end %>
</main>

<%= turbo_frame_tag dom_id(@customer, :total) do %>
  <%= render "customers/total", customer: @customer %>
<% end %>

app/views/customers/update.turbo_stream.erb
<%= turbo_stream.replace @customer %>
<%= render_turbo_stream_flash_messages %>