config/routes.rb
Rails.application.routes.draw do
  root "customers#index"
  
  devise_for :users

  get '/search', to: 'search#index'
  
  resources :customers do
    resources :product_item_dates, except: [:index, :show] do
      resources :product_items, except: [:index, :show], path: 'purchase'
    end
  end

  resources :products

  resources :stores

end

app/views/layouts/_customer_search.html.erb
<form class="d-block w-100 disabled" role="search">
    <input class="form-control me-2" type="search" placeholder="Search customer" aria-label="Search" data-bs-toggle="modal" data-bs-target="#exampleModal" style="cursor: pointer">
</form>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Search customer</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <%= simple_form_for "", url: search_path, method: :get, wrapper: :inline_form, html: { class: "form" } do |f| %>
                    <%= f.error_notification %>
                    <div class="row">
                        <div class="col-12">
                            <%= f.input :name, input_html: { autofocus: true, placeholder: 'Customer name' }, label: false %>
                        </div>

                        <!--<div class="col-12">
                            <%#= f.input :payment_status, as: :select, collection: ProductItem.payment_statuses.keys, include_blank: "Select payment status", wrapper_html: { class: "line-item__description" }, label: false %>
                        </div>-->

                        <div class="col-12 text-end">
                            <%= button_tag type: 'submit', class: "butn butn--primary" do %>
                                Search
                                <i class="bi bi-search"></i>
                            <% end %>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div
    class="flash__message"
    data-controller="removals"
    data-action="animationend->removals#remove"
  >
    <i class="bi bi-info-square me-1" style="color: hsl(300.74deg 100% 92.72%);"></i>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark mb-3" style="background:#34063b; box-shadow: var(--shadow-small);">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      -CPM-
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mb-2 mb-lg-0 ms-5">
        <li class="nav-item">
          <%= link_to "STORES", stores_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "CUSTOMERS", customers_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "PRODUCTS", products_path, class: "nav-link" %>
        </li>
      </ul>

      <ul class="navbar-nav mb-2 mb-lg-0 ms-auto">
        
        <!--<li class="nav-item">
        <%#= link_to "Add customer", new_customer_path, class: "butn butn--primary nav-link", data: { turbo_frame: dom_id(Customer.new) } %>-->
        <% if user_signed_in? %>
            <li class="nav-item dropdown">
                <a class="nav-link" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="bi bi-person-circle fs-6"></i>
                    <i class="bi bi-chevron-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-menu-end" style="background:#34063b;">
                    <%= link_to 'Account Settings', edit_user_registration_path, class: "dropdown-item text-white" %>
                    <%= link_to 'Logout', destroy_user_session_path, data: {"turbo-method": :delete}, class: "dropdown-item text-white" %>
                </ul>
            </li>
        <% else %>
            <%= link_to 'Log in', new_user_session_path, class: "nav-link" %>
            <%= link_to 'Sign up', new_user_registration_path, class: "nav-link" %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Customer Payment Tracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <%= favicon_link_tag asset_path('wallet.png') %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div id="flash" class="flash">
      <%= render "layouts/flash" %>
    </div>
    <%= yield %>
    <%#= debug(params) if Rails.env.development? %>
  </body>
</html>